// AUTO-GENERATED by generate-data.js from the website's data files. Do not edit by hand:
// change user/building-info.js or user/accessibility-data.js, re-run generate-data.js, and redeploy.

export const DATA_CHECKED: string = "October 2026";
export const MAP_DATA_SOURCE: string = "WWU campus map data, exported Sep 25, 2026";

export const BUILDINGS: { code: string; name: string; url: string; accessibility: string[]; genderNeutral: string | null; note: string | null; source: string }[] = [
 {
  "code": "AA",
  "name": "Art Annex",
  "url": "https://www.wwu.edu/building/aa",
  "accessibility": [
   "Accessible parking to the east",
   "Accessible entrance: a manual (not button-activated) accessible entrance on the west side",
   "No accessible restrooms are provided",
   "Only the basement is wheelchair accessible"
  ],
  "genderNeutral": "AA 266",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "AB",
  "name": "Archives Building",
  "url": "https://www.wwu.edu/building/ab",
  "accessibility": [
   "Accessible entrance: a button-activated entrance on the east side",
   "An accessible restroom on the first floor",
   "An elevator serves both floors",
   "Accessible parking to the east"
  ],
  "genderNeutral": "AB 204, 208",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "AC",
  "name": "Administrative Services Center",
  "url": "https://www.wwu.edu/building/ac",
  "accessibility": [
   "Accessible parking to the west",
   "Accessible entrances on the west side of the building",
   "Accessible restrooms on all floors",
   "Elevator to all floors"
  ],
  "genderNeutral": null,
  "note": "Located off campus at 333 32nd Street. A parking permit is required in lot 32G Monday through Friday.",
  "source": "Western Washington University"
 },
 {
  "code": "AH",
  "name": "Arntzen Hall",
  "url": "https://www.wwu.edu/building/ah",
  "accessibility": [
   "Accessible entrances: button-activated entrances on the west side",
   "Elevators provide access to all levels",
   "Accessible restrooms on the Concourse level (basement)",
   "Access to the Environmental Studies building through the basement connection",
   "Accessible parking to the east (Lot 17 G)"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "AI",
  "name": "Academic Instructional Center",
  "url": "https://www.wwu.edu/building/ai",
  "accessibility": [
   "Accessible parking to the east and west of the building",
   "Accessible entrances: button-activated entrances on the north and east sides",
   "Accessible restrooms on each floor",
   "Both elevators serve all floors",
   "Academic Instructional Center West is reachable via the 4th-floor sky-bridge"
  ],
  "genderNeutral": "See Academic Instructional Center West",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "AW",
  "name": "Academic Instructional West",
  "url": "https://www.wwu.edu/building/aw",
  "accessibility": [
   "Accessible parking to the east and west of the building",
   "Accessible entrances: button-activated entrances on the north and east sides",
   "Accessible restrooms on each floor",
   "Both elevators serve all floors",
   "The two Academic Instructional buildings are connected by a 4th-floor sky-bridge"
  ],
  "genderNeutral": "AW 411",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "BH",
  "name": "Bond Hall",
  "url": "https://www.wwu.edu/building/bh",
  "accessibility": [
   "Accessible entrances: button-activated entrances on the northeast side",
   "An elevator reaches all floors except the 2nd and 3rd half floors (both half floors are reachable by ramps or lifts)",
   "Accessible restrooms on the Mezzanine level",
   "Many doors in this building are 2 ft 8 in wide",
   "Accessible parking to the east or west"
  ],
  "genderNeutral": "BH 157, 207, 307, 403B",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "BI",
  "name": "Biology",
  "url": "https://www.wwu.edu/building/bi",
  "accessibility": [
   "Accessible entrance: a button-activated entrance on the northeast corner",
   "Accessible restrooms on floors 2-5",
   "An elevator provides access to all levels",
   "The Chemistry Building is reachable via a 4th-floor sky bridge",
   "Accessible parking to the east or south"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "BT",
  "name": "Buchanan Towers",
  "url": "https://housing.wwu.edu/life-on-campus/buchanan-towers",
  "accessibility": [
   "Both Buchanan Towers and Buchanan Towers East are ADA accessible buildings with elevators throughout",
   "Accessible entrances on the north and south sides",
   "Accessible restrooms in the main lounge on the 1st floor",
   "Resident parking: lot 1R (permit required), ADA accessible"
  ],
  "genderNeutral": "351 & 352",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "CA",
  "name": "Canada House",
  "url": "https://www.wwu.edu/building/ca",
  "accessibility": [
   "Accessible entrance: a button-activated entrance on the east side",
   "Only the first floor is wheelchair accessible",
   "An accessible restroom on the first floor",
   "Accessible parking to the south (Lot 11G)"
  ],
  "genderNeutral": "CA 105, 204",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "CB",
  "name": "Morse Hall / Chemistry Building",
  "url": "https://www.wwu.edu/building/cb",
  "accessibility": [
   "Accessible entrance: a button-activated entrance on the northeast corner",
   "Accessible restrooms on all floors",
   "An elevator provides access to all floors",
   "The Biology building is reachable via the 4th-floor foot bridge",
   "Accessible parking to the east"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "CF",
  "name": "Communications Facility",
  "url": "https://www.wwu.edu/building/cf",
  "accessibility": [
   "Accessible entrances: button-activated entrances on the east and west sides",
   "Accessible restrooms on all floors",
   "Centrally located elevators provide access to all floors",
   "Accessible parking to the east (Lot 17 G)"
  ],
  "genderNeutral": "CF 157",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "CG",
  "name": "Alma Clark Glass Hall",
  "url": "https://housing.wwu.edu/life-on-campus/glass-kappa",
  "accessibility": [
   "ADA accessible building",
   "Elevator access throughout",
   "Accessible entrances",
   "Accessible restrooms throughout",
   "Resident parking: lot 15R (permit required), ADA accessible"
  ],
  "genderNeutral": "168, 169, 445 & 447",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "CH",
  "name": "College Hall",
  "url": "https://www.wwu.edu/building/ch",
  "accessibility": [
   "Accessible entrances: button-activated entrances on the northeast and southwest sides",
   "The west entrance only gives access to rooms 133 (Journalism Lab), 135, 137 (Klipsun) and 141 (Western View)",
   "A wheelchair lift provides access to the second and third floors",
   "Accessible restrooms on the second floor"
  ],
  "genderNeutral": "CH 108A, 130",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "CM",
  "name": "Commissary",
  "url": "https://www.wwu.edu/building/cm",
  "accessibility": [
   "Accessible entrance: a button-activated entrance on the west side",
   "An accessible restroom on the ground floor",
   "Accessible parking to the west (Lot 22G)"
  ],
  "genderNeutral": "CM 103",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "CS",
  "name": "Campus Services",
  "url": "https://www.wwu.edu/building/cs",
  "accessibility": [
   "Accessible entrance: a button-activated entrance on the north side",
   "Accessible restrooms on the ground floor",
   "An elevator provides access to all floors",
   "Accessible parking to the north (Lot 23 V)"
  ],
  "genderNeutral": "CS 102, 103, 127, 128",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "CV",
  "name": "Carver",
  "url": "https://www.wwu.edu/building/cv",
  "accessibility": [
   "Accessible entrances: button-activated entrances on the northeast and southwest sides",
   "An accessible manual entrance on the southeast side",
   "Only the ground floor is accessible",
   "Accessible restrooms in the southeast corridor and the locker rooms",
   "Some doors are 2 ft 10 in wide",
   "There are two elevators",
   "Accessible parking to the north of the building"
  ],
  "genderNeutral": "CV 111 (incl. shower & lockers), 226, 227, 309, 310, 311",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "EH",
  "name": "Edens Hall",
  "url": "https://housing.wwu.edu/life-on-campus/edens-higginson",
  "accessibility": [
   "ADA accessible building",
   "Elevator access throughout",
   "Accessible entrances on the south and west sides",
   "Accessible restrooms on the first floor",
   "Resident parking: lot 3R (permit required), ADA accessible"
  ],
  "genderNeutral": "212A",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "EN",
  "name": "Edens Hall North",
  "url": "https://housing.wwu.edu/life-on-campus/edens-higginson",
  "accessibility": [
   "Accessible entrance on the northwest side",
   "Only the 1st floor is currently wheelchair accessible; the elevator has been decommissioned due to safety issues",
   "No accessible restrooms",
   "Resident parking: lot 3R (permit required), ADA accessible"
  ],
  "genderNeutral": "None",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "ES",
  "name": "Environmental Studies",
  "url": "https://www.wwu.edu/building/es",
  "accessibility": [
   "Accessible entrances: button-activated entrances on the north and south sides",
   "The west elevator reaches all floors, including split levels",
   "The east elevator only reaches whole levels",
   "Accessible restrooms on the ground floor",
   "Arntzen Hall is accessible from the ground floor",
   "Accessible parking to the east (Lot 17-G)"
  ],
  "genderNeutral": "ES 120, 521",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "ET",
  "name": "Ross Engineering Technology",
  "url": "https://www.wwu.edu/building/et",
  "accessibility": [
   "Accessible entrance: a button-activated entrance on the north side",
   "The south entrance is NOT wheelchair accessible, despite the ramp",
   "An elevator provides access to all floors",
   "Accessible restrooms on floors 1 and 3",
   "Accessible parking to the south",
   "Accessible parking to the east (Lot 17G)"
  ],
  "genderNeutral": "Inside suite 204",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "FA",
  "name": "Fairhaven Academic Building / Fairhaven College",
  "url": "https://www.wwu.edu/building/fa",
  "accessibility": [
   "Accessible entrances: button-activated entrances on the north and south sides",
   "Wheelchair access from the courtyard or from the parking lot on the north side",
   "An elevator reaches all floors, but a key is needed for the second-floor dining area (contact Fairhaven Dining Services at 650-6851)",
   "Accessible restrooms on the first and third floors",
   "College administrative offices are on the 3rd floor",
   "Accessible parking to the north and/or west"
  ],
  "genderNeutral": "FA 120",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "FI",
  "name": "Fine Arts",
  "url": "https://www.wwu.edu/building/fi",
  "accessibility": [
   "Accessible entrances: a button-activated entrance on the northwest side",
   "An accessible manual entrance on the southwest side",
   "An elevator serves the first and second floors",
   "The third floor and basement are not wheelchair accessible",
   "Rooms 123, 125 and 125a are reachable by wheelchair lift",
   "Accessible restrooms on the first floor",
   "The first-floor computer lab at the north end is accessible",
   "Western Gallery: the northwest entrance is accessible",
   "Accessible parking to the southeast"
  ],
  "genderNeutral": "FI 126, 128",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "FR",
  "name": "Fraser Hall",
  "url": "https://www.wwu.edu/building/fr",
  "accessibility": [
   "Accessible entrance: a button-activated entrance on the west side",
   "There are no accessible restrooms in this building",
   "Accessible parking to the east (Lot 10G)"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "FX",
  "name": "Fairhaven Complex",
  "url": "https://housing.wwu.edu/life-on-campus/fairhaven",
  "accessibility": [
   "The complex has 12 stacks: stacks 1-10 are NOT ADA accessible and have no elevators",
   "Stacks 11-12 are ADA accessible and have elevators",
   "The wheelchair entrance is through the main courtyard entrance",
   "An accessible restroom is in the stack 11 4th-floor TV lounge",
   "Resident parking: lot 18R (permit required), ADA accessible"
  ],
  "genderNeutral": "Stacks 1-10: floor 1; stack 11: floor 4",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "HG",
  "name": "Higginson Hall",
  "url": "https://housing.wwu.edu/life-on-campus/edens-higginson",
  "accessibility": [
   "ADA accessible building",
   "Elevator access throughout",
   "Accessible entrances on the northwest and southeast sides",
   "Accessible restroom in the 1st-floor lounge",
   "Resident parking: lot 3R (permit required), ADA accessible"
  ],
  "genderNeutral": "172",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "HH",
  "name": "Haggard Hall",
  "url": "https://www.wwu.edu/building/hh",
  "accessibility": [
   "Accessible entrances: button-activated entrances on the northwest, northeast and southeast sides",
   "The northeast entrance is under the Haggard Hall/Wilson Library sky-bridge",
   "Elevators provide access to all floors",
   "The elevator near High Street only serves classrooms on all floors, not the library",
   "The central elevator only connects floors 2 and 3 of the library",
   "Accessible restrooms on all floors",
   "The second-floor sky-bridge provides wheelchair access to Wilson Library",
   "Accessible parking on the southwest side of the building"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "HS",
  "name": "High Street Hall",
  "url": "https://www.wwu.edu/building/hs",
  "accessibility": [
   "Accessible entrance: button-activated entrances in the courtyard",
   "There are no accessible restrooms in this building",
   "Accessible parking to the east (Lot 11G)"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "HU",
  "name": "Humanities Building",
  "url": "https://www.wwu.edu/building/hu",
  "accessibility": [
   "Accessible entrances: button-activated entrances on the northeast and southeast sides",
   "An elevator provides access to floors 1-3",
   "Accessible restrooms on the second floor",
   "Accessible parking to the east (Lot 10G)"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "MA",
  "name": "Mathes Hall",
  "url": "https://housing.wwu.edu/life-on-campus/mathes",
  "accessibility": [
   "NOT an ADA accessible building",
   "Accessible entrance off Garden St",
   "Access up to the 8th floor only",
   "No accessible restrooms",
   "The computer lab and TV lounge on the 9th floor are not accessible",
   "Accessible parking: lot 6V (permit required)"
  ],
  "genderNeutral": "128A & 128B",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "MH",
  "name": "Miller Hall",
  "url": "https://www.wwu.edu/building/mh",
  "accessibility": [
   "This building is fully ADA compliant",
   "Accessible entrances on the southeast and northwest sides",
   "Accessible parking on the southeast side"
  ],
  "genderNeutral": "MH 413",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "NA",
  "name": "Nash Hall",
  "url": "https://housing.wwu.edu/life-on-campus/nash",
  "accessibility": [
   "ADA accessible building",
   "The wheelchair-accessible entrance is the side door facing High St",
   "The basement through floor 6 are wheelchair accessible",
   "Accessible restrooms on the 4th (women's) and 5th (men's) floors",
   "The computer lab on the 7th floor is not accessible",
   "Accessible parking: the turnaround on the south side"
  ],
  "genderNeutral": "Basement and 1st floor",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "OM",
  "name": "Old Main",
  "url": "https://www.wwu.edu/building/om",
  "accessibility": [
   "Accessible parking to the east of the building",
   "Accessible entrances on the south and east sides",
   "Accessible restrooms on the 1st, 3rd and 5th floors",
   "The south elevator serves floors 1-4 and only Room 530 on the 5th floor",
   "The north elevator serves floors 2-4 and Rooms 560-587 on the 5th floor"
  ],
  "genderNeutral": "OM 100A, 100B, 567, and inside suites 200, 300 & 400",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "PA",
  "name": "Performing Arts Center",
  "url": "https://www.wwu.edu/building/pa",
  "accessibility": [
   "Accessible parking on the southwest side of the building",
   "Accessible entrances (WWU's page gives no location details)",
   "Accessible restrooms (WWU's page gives no location details)"
  ],
  "genderNeutral": "PA 150A, 151A, 390",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "PH",
  "name": "Parks Hall",
  "url": "https://www.wwu.edu/building/ph",
  "accessibility": [
   "Accessible parking to the south of the building",
   "Accessible entrances on the south, east and north sides",
   "Accessible restrooms on all floors in the central hallways"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "PP",
  "name": "Physical Plant",
  "url": "https://www.wwu.edu/building/pp",
  "accessibility": [
   "Accessible parking to the west and south (Lot 24G)"
  ],
  "genderNeutral": "PP 214",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "RA",
  "name": "Ridgeway Alpha",
  "url": "https://housing.wwu.edu/life-on-campus/soda",
  "accessibility": [
   "NOT an ADA accessible building",
   "No elevator",
   "Resident parking: lot 15R (permit required), ADA accessible"
  ],
  "genderNeutral": "1st floor",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "RC",
  "name": "Ridgeway Commons",
  "url": "https://housing.wwu.edu/life-on-campus/soda",
  "accessibility": [],
  "genderNeutral": null,
  "note": "WWU's page for this building does not list accessibility details.",
  "source": "WWU University Residences"
 },
 {
  "code": "RD",
  "name": "Ridgeway Delta",
  "url": "https://housing.wwu.edu/life-on-campus/soda",
  "accessibility": [
   "NOT an ADA accessible building",
   "No elevator",
   "Resident parking: lot 15R (permit required), ADA accessible"
  ],
  "genderNeutral": "2nd floor",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "RK",
  "name": "Ridgeway Kappa",
  "url": "https://housing.wwu.edu/life-on-campus/glass-kappa",
  "accessibility": [
   "NOT an ADA accessible building",
   "No elevator",
   "Resident parking: lot 15R (permit required), ADA accessible"
  ],
  "genderNeutral": "1st & 2nd floors",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "RO",
  "name": "Ridgeway Omega",
  "url": "https://housing.wwu.edu/life-on-campus/soda",
  "accessibility": [
   "NOT an ADA accessible building",
   "No elevator",
   "Resident parking: lot 15R (permit required), ADA accessible"
  ],
  "genderNeutral": "2nd floor",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "RS",
  "name": "Ridgeway Sigma",
  "url": "https://housing.wwu.edu/life-on-campus/soda",
  "accessibility": [
   "NOT an ADA accessible building",
   "No elevator",
   "Resident parking: lot 15R (permit required), ADA accessible"
  ],
  "genderNeutral": "2nd floor",
  "note": null,
  "source": "WWU University Residences"
 },
 {
  "code": "SL",
  "name": "SMATE / Science Lecture",
  "url": "https://www.wwu.edu/building/sl",
  "accessibility": [
   "Accessible doors at the south and west entrances",
   "Accessible restrooms on all floors",
   "Accessible parking to the south"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "SV",
  "name": "Wade King Recreation Center",
  "url": "https://www.wwu.edu/building/sv",
  "accessibility": [
   "Accessible parking to the northeast (Lot 19G)",
   "Accessible entrances on the east side",
   "Accessible restrooms on the main floor"
  ],
  "genderNeutral": "SV 110, 155, 156",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "VC",
  "name": "Viking Commons",
  "url": "https://www.wwu.edu/building/vc",
  "accessibility": [
   "Accessible restrooms on the main level near the entrance",
   "Accessible parking to the north (Lot 6V)"
  ],
  "genderNeutral": null,
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "VU",
  "name": "Viking Union",
  "url": "https://www.wwu.edu/building/vu",
  "accessibility": [
   "Automatic doors at High St. and the VU Plaza on the 6th floor, and on the 1st floor at the Garden St. entrance",
   "Accessible restrooms on floors 3, 4, 5 and 6",
   "Accessible parking on the north side of the building (Lot 6V)"
  ],
  "genderNeutral": "VU 351, 353, 714, 715, 716, 717",
  "note": null,
  "source": "Western Washington University"
 },
 {
  "code": "WL",
  "name": "Wilson Library",
  "url": "https://www.wwu.edu/building/wl",
  "accessibility": [
   "Accessible entrances via the Haggard Hall sky bridge, or at the southeast corner",
   "Accessible restrooms on the first floor (or in Haggard Hall)",
   "Wheelchair access via the Haggard Hall library entrances, then across the sky bridge",
   "The southwest elevator (near the Media/Circulation desk) serves floors 2-6",
   "The east and west elevators serve floors 1-5"
  ],
  "genderNeutral": "WL 165A (within DAC); 182 (open all hours); 668 & 669 (Mon-Fri 8 am-4 pm)",
  "note": null,
  "source": "Western Washington University"
 }
];

export const LAYER_LINES: { label: string; items: string[] }[] = [
 {
  "label": "Accessible entrances",
  "items": [
   "Accessible Entrance (NH)",
   "Accessible Entrance (EH) (x2)",
   "Accessible Entrances (FA)",
   "Accessible Entrance (AB)",
   "Accessible Entrance (BT)",
   "Accessible Entrance (CS)",
   "Accessible Entrance (RC)",
   "Accessible Entrance (CG)",
   "Accessible Entrance (CA)",
   "Accessible Entrance (HS)",
   "Accessible Entrance (HG) - High Street",
   "Accessible Entrance (EN)",
   "Accessible Entrance (VC)",
   "Accessible Entrance (VU)",
   "Accessible Entrance (PA)",
   "Accessible Entrance (OM)",
   "Accessible Entrance (HU)",
   "Accessible Entrance (FR)",
   "Accessible Entrance (MH)",
   "Accessible Entrance (FI)",
   "Accessible Entrance (HH)",
   "Accessible Entrance (BH)",
   "Accessible Entrance (CV)",
   "Accessible Entrance (SL) south",
   "Accessible Entrance (ET)",
   "Accessible Entrance (PH) — These markers represent the location of accessible entries/exits for campus buildings.",
   "Accessible Entrance (ES) 1",
   "Accessible Entrance (CF)",
   "Accessible Entrance (AI)",
   "Accessible Entrance (AW)",
   "Accessible Entrance (Atrium Market)",
   "Accessible Entrance (Artzen Hall)",
   "Accessible Entrance (HG) - 2",
   "Accessible Entrance (HG) - 3",
   "Accessible Entrance (FR) -2",
   "Accessible Entrance (OM) - 2",
   "Accessible Entrance (HU) 2",
   "Accessible Entrance (MH) 4",
   "Accessible Entrance (MH) 3",
   "Accessible Entrance (MH) 2",
   "Accessible Entrance (BH) 2",
   "Accessible Entrance (HH) 2",
   "Accessible Entrance (HH) 3",
   "Accessible Entrance (VU) 2",
   "Accessible Entrance (VU) 3",
   "Accessible Entrance (PA) 2",
   "Accessible Entrance (HS) 2",
   "Accessible Entrance (CH)",
   "Accessible Entrance (CV) 2",
   "Accessible Entrance (CV) 3",
   "Accessible Entrance (CV) 4",
   "Accessible Entrance (CG) North",
   "Accessible Entrance (SL) 2",
   "Accessible Entrance (SL) 3",
   "Accessible Entrance (CB Chemistry, Morse Hall) 1)",
   "Accessible Entrance (CB Chemistry, Morse Hall) 2",
   "Accessible Entrance (Artzen Hall AH)",
   "Accessible Entrance (ES) 2",
   "Accessible Entrance (ES) 3",
   "Accessible Entrance (CF) 2",
   "Accessible Entrance (CF) 3",
   "Accessible Entrance (CF) 4",
   "Accessible Entrance (KB)",
   "Accessible Entrance (KB) 2",
   "Accessible Entrance (AI) 2",
   "Accessible Entrance (AW) 2",
   "Accessible Entrance (AW) 3",
   "Accessible Entrance (FA) 2",
   "Accessible Entrance (BT) 2",
   "Accessible Entrance (BT) 3",
   "Accessible Entrance (CM Commissary)",
   "Accessible Entrance (Student Recreation Center, Wade King SV)",
   "Accessible Entrance (IS)",
   "Accessible Entrance (Biology BI)"
  ]
 },
 {
  "label": "Accessible parking",
  "items": [
   "Nash Hall, Accessible Parking Space — Nash entry",
   "Viking Union (VU) Accessible Parking Space — 6V - Viking Union",
   "Van Accessible Parking Space — 11G - High Street Hall (x2)",
   "Canada House Accessible Parking Space — 11G - Canada House. To park in these spaces legally, a vehicle must display a valid disability parking permit, placard, or license plate.",
   "10G Old Main Accessible Parking Space — 10G - Old Main",
   "10G Fraser Hall Accessible Parking Space — 10G - Fraser Hall. To park in these spaces legally, a vehicle must display a valid disability parking permit, placard, or license plate.",
   "Van Accessible Parking Space — 10G - Fraser Hall",
   "Edens Hall, Accessible Parking Space — Edens HallTo park in these spaces legally, a vehicle must display a valid disability parking permit, placard, or license plate.",
   "10G Fraser Hall, Accessible Parking Space 2 — 10G - Fraser HallTo park in these spaces legally, a vehicle must display a valid disability parking permit, placard, or license plate.",
   "8G Old Main, Accessible Parking Space — 8G - Old MainTo park in these spaces legally, a vehicle must display a valid disability parking permit, placard, or license plate.",
   "Edens Hall, Van Accessible Parking Space — Edens HallTo park in these spaces legally, a vehicle must display a valid disability parking permit, placard, or license plate.",
   "Accessible Parking Space — 10G - Miller Hall (x2)",
   "Accessible Parking Space — Haggard Hall",
   "Accessible Parking Space — 10G - Fine Arts",
   "Accessible Parking Space — 15R - Ridgeway Commons",
   "Accessible Parking Space — CBS - SMATE",
   "Van Accessible Parking Space — 6V - Viking Union",
   "Accessible Parking Space — 29G - Fairhaven",
   "Van Accessible Parking Space — 29G - Fairhaven",
   "Van Accessible Parking Space — 12G - Fairhaven entry",
   "Accessible Parking Space — 12G - Fairhaven entry",
   "Accessible Parking Space — 23V - Campus Services",
   "Accessible Parking Space — OB - Outback",
   "Van Accessible Parking Space — 23V - Campus Services",
   "Accessible Parking Space — 13A - Physical Plant",
   "Accessible Parking Space — Archives Building (25th St.)",
   "Accessible Parking Space — 32G - Administrative Services Center (x2)",
   "Accessible Parking Space — 27R - Birnam Wood (west)",
   "Accessible Parking Space — 22G - Commissary",
   "Accessible Parking Space — 1R - Buchanan Towers",
   "Van Accessible Parking Space — 10G - Miller Hall",
   "Van Accessible Parking Space — Harrington Field",
   "Accessible Parking Space — Harrington Field",
   "Van Accessible Parking Space — C/CR - Recreation Cemter",
   "Accessible Parking Space — C/CR - Recreation Cemter",
   "Van Accessible Parking Space — 19G",
   "Accessible Parking Space — 19G",
   "House of Healing Accessible Parking - 1 — To park in these spaces legally, a vehicle must display a valid disability parking permit, placard, or license plate.",
   "House of Healing Accessible Parking - 2 — To park in these spaces legally, a vehicle must display a valid disability parking permit, placard, or license plate."
  ]
 },
 {
  "label": "Elevators",
  "items": [
   "Elevator, Nash Hall — Elevator provides access to all floors except the 7th floor.",
   "Elevator, Mathes Hall",
   "Elevator, Viking Union — Elevators provide access to all levels. (x4)",
   "Elevator, Viking Commons — Elevator provides access to all floors. Request access from employees.",
   "South Elevator, Old Main — The south elevator provides access to floors 1-4 and room 530 on the 5th floor.",
   "Elevator, Humanities Building — Elevator provides access to floors 1-3.",
   "Elevator, Bookstore",
   "North Elevator, Old Main — The north elevator provides access to floors 2-4 and rooms 560-587 on the 5th floor.",
   "Wilson Library, East Elevator — Elevator provides access to levels 1-5.",
   "West Elevator, Wilson Library — Elevator provides access to levels 1-5.",
   "Elevator, Fraser Hall — Elevator provides access to all floors.",
   "Southwest Elevator, Wilson Library — Elevator provides access to levels 2-6.",
   "Haggard Hall Central Elevator — Elevator only provides access between floors 2 and 3 of the library (no access to the classrooms)",
   "West Library, Haggard Hall — Elevator only provides access to classrooms (all floors), not the library.",
   "South Elevator, Performing Arts Center (PAC) — Elevator provides access to the dressing rooms and floors 1-3.",
   "North Elevator, Performing Arts Center (PAC) — Elevator provides access to floors LL2, LL1, 1 and 2",
   "Elevator, Higginson Hall — Elevator provides access to all floors.",
   "Elevator, Edens Hall — Elevator is not accessible.",
   "South Elavator, Miller Hall — Elevators provide access to all floors and split levels.",
   "North Elevator, Miller Hall — Elevators provide access to all floors and split levels.",
   "Elevator, Bond Hall — Elevator provides access to all floors except the 2nd and 3rd half floors. Both half floors are accessible via ramps.",
   "Wheelchair Lift, Fine Arts — Wheelchair lift provides access to rooms 123, 125 and 125a.",
   "Elevator, Fine Arts — Elevator provides access to the first and second floors.",
   "Elevator, Ross Engineering Technology — Elevator provides access to all floors.",
   "Elevator, Biology Building — Elevator provides access to all floors.",
   "North Elevator, Morse Hall Chemistry Building — Elevator provides access to all floors.",
   "Elevator, Arntzen Hall — Elevators provide access to all floors.",
   "South Elevator, Morse Hall Chemistry Building — Elevator provides access to all floors.",
   "Elevator, SMATE (Science, Math & Technology Education) — Elevator provides access to all floors.",
   "Elevator, Parks Hall — Elevators provide access to all floors.",
   "Environmental Studies, East Elevator, — This elevator provides access to full floors only (not split levels)",
   "Elevator, Communications Facility — Elevators provide access to all floors.",
   "Elevator, Academic Instructional Center West — Elevator provides access to all floors.",
   "West Elevator, Academic Instructional Center — Elevators provide access to all floors.",
   "Academic Instructional Center, East Elevator — Elevators provide access to all floors.",
   "West Elevator, Environmental Studies — Elevator provides access to all floors (inclduing split levels)",
   "Fairhaven College Tower 11-12 Elevator (Residence) — Elevator provides access to all floors.",
   "Elevator, Washington State Archives Building — Elevator provides access to all floors.",
   "West Elevator, Buchanan Towers (Residence) — Elevator provide access to all floors. (x2)",
   "Elevator, Fairhaven College — Eelevator provides access to all floors. A key is needed to access the 2nd floor dining area. Contact Fairhaven Dining Services",
   "Elevator, Wade King Recreation Center — Elevator provides access to all floors.",
   "Elevator, Campus Services — Elevator provides access to all floors.",
   "North Elevator, Haggard Hall — Elevator only provides access between floors 1 and 2 of the library (no access to the classrooms)",
   "Wheelchair Lift, College Hall — Wheelchair lift proveds lift provides access to the second and third floors."
  ]
 },
 {
  "label": "Accessible restrooms (listed on WWU's map as gender-neutral and tagged accessible)",
  "items": [
   "Gender Neutral Restroom – Fairhaven Stack 11 (FX11) — Accessible, Gender Neutral restroom - located in the fourth floor lounge of Fairhaven Stack 11.",
   "Gender Neutral Restroom – Miller Hall — Located on MH-413",
   "Gender Neutral Restroom – Morse Hall Chemistry Building — Located in the basement. Located on CB-192 & CB-193",
   "Gender Neutral Restroom – Carver Building — CV-111 includes a shower and lockers. Located on CV-111, CV-226, CV-227, CV-309, CV-310 & CV-311",
   "Gender Neutral Restroom – Viking Union — Gender neutral restooms on the 3rd and 7th floor are ADA accessible. Located on VU-351, VU-353, VU-714, VU-715, VU-716 & VU-717",
   "Gender Neutral Restroom – Performing Arts Center — Accessible, Gender Neutral restroom located on the 3rd floor. Located on PA-150A, PA-151A & PA-390",
   "Gender Neutral Restroom – Wilson Library — WL-165A & WL-182 are ADA accessible Located on WL-165A (within the DAC), WL-182, WL-668 & WL-669",
   "Gender Neutral Restroom – Haggard Hall — An Accessible, Gender Neutral Restroom is located on the 2nd floor. Located on HH-241",
   "Gender Neutral Restroom – Bond Hall — Accessible, Gender Neutral restrooms are located on the Mezzanie and floors 2, 3 & 4 by the elevator. Located on BH-157, BH-207, BH-307 & BH",
   "Gender Neutral Restroom – Fine Arts Building — Located on FI-126 & FI-128",
   "Gender Neutral Restroom – College Hall — CH-108A is ADA accessible. Located on CH-108A & CH-130",
   "Gender Neutral Restroom – Environmental Studies Building — ES-120 is ADA accessible. Located on ES-120 & ES-521",
   "Gender Neutral Restroom – Communications Facility — Accessible, Gender Neutral restroom located on the 1st floor. Located on CF-157",
   "Gender Neutral Restroom – Academic Instructional Center (West) — Located on AW-411",
   "Gender Neutral Restroom – Wade King Student Recreation Center — Accessible, Gender Neurtral restrooms and Changing Room / Shower are located on the 1st floor. Located on SV-110, SV-155 & SV-156",
   "Gender Neutral Restroom – Fairhaven College Building — Accessible, Gender Neutral Restroom is located on the 1st floor. Located on FA-120",
   "Gender Neutral Restroom – Commissary Building — An Accessible, Gender Neutral restroom is located on the ground floor. Located on CM-103",
   "Gender Neutral Restroom – Campus Services — Accessible, Gender Neutral restrooms are located on the ground floor. Located on CS-102, CS-103, CS-127 & CS-128",
   "Gender Neutral Restroom – Wa State Archives Building — Accessible, Gender Neutral restrooms are located on main floor. Located on AB-204 & AB-208",
   "Gender Neutral Restroom – Ridgeway Commons — Located on RC-114A",
   "Gender Neutral Restroom – Old Main Building — OM-100A, OM-100B & OM-567 are ADA accessible. Located on OM-100A, OM-100B & OM-567, and inside suites 200, 300, 330 & 400",
   "Gender Neutral Restroom – Physical Plant — Accessible, Gender Neutral restroom located on the 1st floor (limited access). Located on PP-214",
   "Gender Neutral Restroom – Alma Clark Glass Hall — CG-169, CG-445 & CG-447 are ADA accessible. Located on CG-168, CG-169, CG-445 & CG-447"
  ]
 }
];

export const RESOURCES: { id: string; name: string; url: string; about: string }[] = [
 {
  "id": "dac",
  "name": "Disability Access Center (DAC)",
  "url": "https://disability.wwu.edu/",
  "about": "WWU's office that administers reasonable accommodations for disabled students across academics, on-campus housing, and Western programs and services. Location: Wilson Library 170 (516 High Street). Phone 360-650-3083. Email drsfrontdesk@wwu.edu."
 },
 {
  "id": "doc",
  "name": "Disability Outreach Center (Associated Students)",
  "url": "https://mss.wwu.edu/sairc/disability-outreach-center",
  "about": "A student-led resource for students with disabilities and community allies. For accommodations in classes, people should contact the Disability Access Center. Check the page for its current location and contacts."
 },
 {
  "id": "housing-accommodations",
  "name": "Disability accommodations for on-campus housing (University Residences)",
  "url": "https://housing.wwu.edu/disability-accommodation",
  "about": "University Residences' page about disability accommodations in on-campus housing."
 },
 {
  "id": "atus",
  "name": "Academic Technology and User Services (ATUS)",
  "url": "https://atus.wwu.edu",
  "about": "Offers services that help make technology and digital content accessible for the Western community."
 },
 {
  "id": "transportation",
  "name": "Transportation Services",
  "url": "https://transportation.wwu.edu/",
  "about": "Parking information and maps for campus, including visitor, evening and weekend, permit, and residence parking."
 },
 {
  "id": "wwu-map",
  "name": "WWU's official campus map",
  "url": "https://map.wwu.edu/?id=2303",
  "about": "WWU's own interactive campus map. It has an Accessibility layer showing official accessibility features."
 },
 {
  "id": "accessibility-notice",
  "name": "WWU Accessibility Notice",
  "url": "https://www.wwu.edu/commitment-accessibility",
  "about": "WWU's statement about its commitment to accessibility."
 },
 {
  "id": "emergency",
  "name": "Emergency and weather information",
  "url": "https://emergency.wwu.edu/",
  "about": "WWU's emergency alerts and weather information. In an emergency, call 911."
 }
];
