// Builds data.ts (what the AI assistant knows) from the website's own data files, so the
// assistant and the map can never drift apart. Run this from inside this folder whenever
// building-info.js or accessibility-data.js changes, then redeploy the function:
//
//     node generate-data.js            (reads ../../../user/*.js, i.e. the repo's user/ folder)
//     node generate-data.js path/to/user
//
// Nothing here is fetched from the internet; it only reads those files and the resource list below.

const fs = require("fs"), path = require("path"), vm = require("vm");
const userDir = path.resolve(process.argv[2] || path.join(__dirname, "..", "..", "..", "user"));
const read = f => fs.readFileSync(path.join(userDir, f), "utf8");

function load(file, exportName) {
    const ctx = {}; vm.createContext(ctx);
    vm.runInContext(read(file) + `\nthis.__out = ${exportName};`, ctx);
    return ctx.__out;
}

const info = load("building-info.js", "WWU_BUILDING_INFO");
const checked = load("building-info.js", "WWU_BUILDING_INFO_CHECKED");
const features = load("accessibility-data.js", "ACCESSIBILITY_FEATURES");
const featuresSource = load("accessibility-data.js", "ACCESSIBILITY_DATA_SOURCE");

// building code -> full name, taken from the names the site already uses, e.g. "Miller Hall (MH)"
const names = {};
for (const m of read("make_report.js").matchAll(/"([^"\n]*\(([A-Z]{2,3})\))"/g)) names[m[2]] = m[1].replace(/\s*\([A-Z]{2,3}\)\s*$/, "");

const buildings = Object.keys(info).sort().map(code => ({
    code,
    name: names[code] || code,
    url: info[code].url,
    accessibility: info[code].accessibility,
    genderNeutral: info[code].genderNeutral || null,
    note: info[code].note || null,
    source: info[code].source,
}));

// Map-layer points: only the kinds that are meaningful as text. The ~120 route points are single
// dots on a line with no useful words, so they're left out.
const LAYERS = [
    ["accessible_entrance", "Accessible entrances"],
    ["accessible_parking", "Accessible parking"],
    ["elevator", "Elevators"],
    ["accessible_restroom", "Accessible restrooms (listed on WWU's map as gender-neutral and tagged accessible)"],
];
const clean = s => String(s || "").replace(/\s+/g, " ").trim().slice(0, 140);
const layerLines = LAYERS.map(([type, label]) => {
    const counts = new Map();
    for (const f of features.filter(x => x.type === type)) {
        const key = clean(f.title) + (clean(f.description) ? " — " + clean(f.description) : "");
        counts.set(key, (counts.get(key) || 0) + 1);
    }
    return { label, items: [...counts.entries()].map(([text, n]) => n > 1 ? `${text} (x${n})` : text) };
});

// Official WWU resources. Every fact here came from a WWU page; links are WWU's own.
const resources = [
    { id: "dac", name: "Disability Access Center (DAC)", url: "https://disability.wwu.edu/",
      about: "WWU's office that administers reasonable accommodations for disabled students across academics, on-campus housing, and Western programs and services. Location: Wilson Library 170 (516 High Street). Phone 360-650-3083. Email drsfrontdesk@wwu.edu." },
    { id: "doc", name: "Disability Outreach Center (Associated Students)", url: "https://mss.wwu.edu/sairc/disability-outreach-center",
      about: "A student-led resource for students with disabilities and community allies. For accommodations in classes, people should contact the Disability Access Center. Check the page for its current location and contacts." },
    { id: "housing-accommodations", name: "Disability accommodations for on-campus housing (University Residences)", url: "https://housing.wwu.edu/disability-accommodation",
      about: "University Residences' page about disability accommodations in on-campus housing." },
    { id: "atus", name: "Academic Technology and User Services (ATUS)", url: "https://atus.wwu.edu",
      about: "Offers services that help make technology and digital content accessible for the Western community." },
    { id: "transportation", name: "Transportation Services", url: "https://transportation.wwu.edu/",
      about: "Parking information and maps for campus, including visitor, evening and weekend, permit, and residence parking." },
    { id: "wwu-map", name: "WWU's official campus map", url: "https://map.wwu.edu/?id=2303",
      about: "WWU's own interactive campus map. It has an Accessibility layer showing official accessibility features." },
    { id: "accessibility-notice", name: "WWU Accessibility Notice", url: "https://www.wwu.edu/commitment-accessibility",
      about: "WWU's statement about its commitment to accessibility." },
    { id: "emergency", name: "Emergency and weather information", url: "https://emergency.wwu.edu/",
      about: "WWU's emergency alerts and weather information. In an emergency, call 911." },
];

const out =
`// AUTO-GENERATED by generate-data.js from the website's data files. Do not edit by hand:
// change user/building-info.js or user/accessibility-data.js, re-run generate-data.js, and redeploy.

export const DATA_CHECKED: string = ${JSON.stringify(checked)};
export const MAP_DATA_SOURCE: string = ${JSON.stringify(featuresSource)};

export const BUILDINGS: { code: string; name: string; url: string; accessibility: string[]; genderNeutral: string | null; note: string | null; source: string }[] = ${JSON.stringify(buildings, null, 1)};

export const LAYER_LINES: { label: string; items: string[] }[] = ${JSON.stringify(layerLines, null, 1)};

export const RESOURCES: { id: string; name: string; url: string; about: string }[] = ${JSON.stringify(resources, null, 1)};
`;
fs.writeFileSync(path.join(__dirname, "data.ts"), out);
console.log(`data.ts written: ${buildings.length} buildings, ${layerLines.map(l => l.items.length).reduce((a, b) => a + b, 0)} map-layer lines, ${resources.length} resources (${out.length} bytes)`);
